import { defaultImageLeft, defaultImageTop } from "../utils/canvasUtils";

const defaultCurUserData = {
    name: {
        type: "text",
        content: "",
        isSprite: true,
        originX: "center",
        left: 1180,
        top: 1765,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
    },
    idNum: {
        type: "text",
        content: "",
        isSprite: true,
        left: 1235,
        top: 1942,
        scaleX: 1,
        scaleY: 1,
        originX: "center",
        angle: 0,
    },
    organization: {
        type: "text",
        content: "",
        isSprite: true,
        left: 946,
        top: 2100,
        scaleX: 1,
        originX: "center",
        scaleY: 1,
        angle: 0,
    },
    certNum: {
        type: "text",
        content: "",
        isSprite: true,
        originX: "center",
        left: 1197,
        top: 2265,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
    },
    expDate: {
        type: "text",
        content: "",
        isSprite: true,
        left: 819,
        top: 2435,
        originX: "center",
        scaleX: 1,
        scaleY: 1,
        angle: 0,
    },
    profileImage: {
        type: "image",
        isSprite: true,
        content: "",
        left: defaultImageLeft,
        top: defaultImageTop,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
    },
    certType: { type: "select", content: "MAAM", isSprite: false },
    issuingAgency: {
        isSprite: false,
        type: "text",
        content: "",
    },
};

export default defaultCurUserData;
